# SonarQube Project Configuration

sonar.projectKey=AddressBookApp
sonar.projectName=AddressBook Application
sonar.projectVersion=1.0

# Path to source code
sonar.sources=.

# Language
sonar.language=cs

# Encoding
sonar.sourceEncoding=UTF-8
